/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as SignInImport } from './routes/sign-in'
import { Route as DetailsImport } from './routes/details'
import { Route as ContactImport } from './routes/contact'
import { Route as AboutImport } from './routes/about'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as homeIndexImport } from './routes/(home)/index'
import { Route as AuthenticateddashboardDashboardImport } from './routes/_authenticated/(dashboard)/dashboard'
import { Route as AuthenticatedcatalogCatalogImport } from './routes/_authenticated/(catalog)/catalog'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  path: '/sign-up',
  getParentRoute: () => rootRoute,
})

const SignInRoute = SignInImport.update({
  path: '/sign-in',
  getParentRoute: () => rootRoute,
})

const DetailsRoute = DetailsImport.update({
  path: '/details',
  getParentRoute: () => rootRoute,
})

const ContactRoute = ContactImport.update({
  path: '/contact',
  getParentRoute: () => rootRoute,
})

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
})

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
})

const homeIndexRoute = homeIndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
})

const AuthenticateddashboardDashboardRoute =
  AuthenticateddashboardDashboardImport.update({
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  })

const AuthenticatedcatalogCatalogRoute =
  AuthenticatedcatalogCatalogImport.update({
    path: '/catalog',
    getParentRoute: () => AuthenticatedRoute,
  })

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthenticatedRoute.addChildren([
    AuthenticatedcatalogCatalogRoute,
    AuthenticateddashboardDashboardRoute,
  ]),
  AboutRoute,
  ContactRoute,
  DetailsRoute,
  SignInRoute,
  SignUpRoute,
  homeIndexRoute,
])

/* prettier-ignore-end */
